name: Hub-Mirror-To-Gitee
on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v1.1
      with:
        src: github/yimo0908
        dst: gitee/yimo0908
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
